[package]
org = "ballerinax"
name = "mssql.driver"
version = "@toml.version@"
authors = ["Ballerina"]
keywords = ["MSSQL", "SQL Server"]
repository = "https://github.com/ballerina-platform/module-ballerinax-mssql.driver"
license = ["Apache-2.0"]
distribution = "2201.11.0-20241112-214900-6b80ab87"

[platform.java21]
graalvmCompatible = true

[[platform.java21.dependency]]
path = "./lib/mssql-jdbc-@mssql.driver.version@.jar"

[[platform.java21.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "mssql.driver-native"
version = "@toml.version@"
path = "../native/build/libs/mssql.driver-native-@project.version@.jar"
