[package]
org = "ballerinax"
name = "mssql.driver"
version = "1.6.0"
authors = ["Ballerina"]
keywords = ["MSSQL", "SQL Server"]
repository = "https://github.com/ballerina-platform/module-ballerinax-mssql.driver"
license = ["Apache-2.0"]
distribution = "2201.8.0"

[platform.java17]
graalvmCompatible = true

[[platform.java17.dependency]]
path = "./lib/mssql-jdbc-10.2.0.jre17.jar"

[[platform.java17.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "mssql.driver-native"
version = "1.6.0"
path = "../native/build/libs/mssql.driver-native-1.6.0.jar"
