[package]
org = "ballerinax"
name = "mssql.driver"
version = "1.6.1"
authors = ["Ballerina"]
keywords = ["MSSQL", "SQL Server"]
repository = "https://github.com/ballerina-platform/module-ballerinax-mssql.driver"
license = ["Apache-2.0"]
distribution = "2201.10.0-20241025-103700-5c9e6a27"

[platform.java21]
graalvmCompatible = true

[[platform.java21.dependency]]
path = "./lib/mssql-jdbc-10.2.0.jre17.jar"

[[platform.java21.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "mssql.driver-native"
version = "1.6.1"
path = "../native/build/libs/mssql.driver-native-1.6.1-SNAPSHOT.jar"
